"""initial_schema

Revision ID: 0a5d18f684cf
Revises: 
Create Date: 2026-04-16 18:26:11.708312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3] / "src"))
from novel_dev.db.models import VectorCompat


# revision identifiers, used by Alembic.
revision: str = '0a5d18f684cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapters',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('volume_id', sa.Text(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('raw_draft', sa.Text(), nullable=True),
    sa.Column('polished_text', sa.Text(), nullable=True),
    sa.Column('score_overall', sa.Integer(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=True),
    sa.Column('review_feedback', sa.JSON(), nullable=True),
    sa.Column('fast_review_score', sa.Integer(), nullable=True),
    sa.Column('fast_review_feedback', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volume_id', 'chapter_number', name='uix_volume_chapter')
    )
    op.create_table('entities',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at_chapter_id', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foreshadowings',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('埋下_chapter_id', sa.Text(), nullable=True),
    sa.Column('埋下_time_tick', sa.Integer(), nullable=True),
    sa.Column('埋下_location_id', sa.Text(), nullable=True),
    sa.Column('相关人物_ids', sa.JSON(), nullable=True),
    sa.Column('回收条件', sa.JSON(), nullable=True),
    sa.Column('回收状态', sa.Text(), nullable=False),
    sa.Column('recovered_chapter_id', sa.Text(), nullable=True),
    sa.Column('recovered_event_id', sa.Text(), nullable=True),
    sa.Column('回收影响', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novel_documents',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('novel_id', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('vector_embedding', VectorCompat(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('novel_state',
    sa.Column('novel_id', sa.Text(), nullable=False),
    sa.Column('current_phase', sa.Text(), nullable=False),
    sa.Column('current_volume_id', sa.Text(), nullable=True),
    sa.Column('current_chapter_id', sa.Text(), nullable=True),
    sa.Column('checkpoint_data', sa.JSON(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('novel_id')
    )
    op.create_table('spaceline',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['spaceline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('anchor_chapter_id', sa.Text(), nullable=True),
    sa.Column('anchor_event_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tick')
    )
    op.create_table('entity_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('target_id', sa.Text(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at_chapter_id', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Text(), nullable=True),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('diff_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'version', name='uix_entity_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_versions')
    op.drop_table('entity_relationships')
    op.drop_table('timeline')
    op.drop_table('spaceline')
    op.drop_table('novel_state')
    op.drop_table('novel_documents')
    op.drop_table('foreshadowings')
    op.drop_table('entities')
    op.drop_table('chapters')
    # ### end Alembic commands ###
