"""add pending_extractions table

Revision ID: eaf5a79edc90
Revises: a073a208ff9b
Create Date: 2026-04-18 07:09:11.843867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf5a79edc90'
down_revision: Union[str, Sequence[str], None] = 'a073a208ff9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_extractions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('novel_id', sa.Text(), nullable=False),
    sa.Column('extraction_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('raw_result', sa.JSON(), nullable=False),
    sa.Column('proposed_entities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_novel_documents_vector'), 'novel_documents', ['vector_embedding'], unique=False, postgresql_ops={'vector_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw', postgresql_where='(vector_embedding IS NOT NULL)')
    op.create_index(op.f('idx_entities_vector'), 'entities', ['vector_embedding'], unique=False, postgresql_ops={'vector_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw', postgresql_where='(vector_embedding IS NOT NULL)')
    op.create_index(op.f('idx_chapters_vector'), 'chapters', ['vector_embedding'], unique=False, postgresql_ops={'vector_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw', postgresql_where='(vector_embedding IS NOT NULL)')
    op.drop_table('pending_extractions')
    # ### end Alembic commands ###
