"""add novel_id to entities timeline spaceline foreshadowings

Revision ID: a198e260c3bf
Revises: 0a5d18f684cf
Create Date: 2026-04-17 08:28:24.245248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a198e260c3bf'
down_revision: Union[str, Sequence[str], None] = '0a5d18f684cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('novel_id', sa.Text(), nullable=True))
    op.add_column('timeline', sa.Column('novel_id', sa.Text(), nullable=True))
    op.add_column('spaceline', sa.Column('novel_id', sa.Text(), nullable=True))
    op.add_column('foreshadowings', sa.Column('novel_id', sa.Text(), nullable=True))
    op.create_table('pending_extractions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('novel_id', sa.Text(), nullable=False),
    sa.Column('extraction_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('raw_result', sa.JSON(), nullable=False),
    sa.Column('proposed_entities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_extractions')
    op.drop_column('foreshadowings', 'novel_id')
    op.drop_column('spaceline', 'novel_id')
    op.drop_column('timeline', 'novel_id')
    op.drop_column('entities', 'novel_id')
    # ### end Alembic commands ###
